---
title: "shinyeyesdeleteme"
output: 
  html_document: 
    toc: yes
    keep_md: yes
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Go to the folder where data are located:
```{r}

setwd("C:/Users/harap/OneDrive/Psychologie Studium/PhD/UBC/Dual mET Plexi/PAPER/data analysis/shiny-eyes") #set this to where your data is located
```

Required libraries:
```{r}
library(rmarkdown)

## load the library for crqa
library(Matrix)
library(tseriesChaos)
library(crqa)

## load the library for plotting
library(tidyverse)
library(ggplot2)
library(ggpubr)

```

Load Data
```{r}

# Set the directory where the CSV files are located
csv_dir <- "C:/Users/harap/OneDrive/Psychologie Studium/PhD/UBC/Dual mET Plexi/PAPER/data analysis/shiny-eyes/dyad_1_to_3"

# Get a list of all the CSV files in the directory
csv_files <- list.files(path = csv_dir, pattern = "*.csv", full.names = TRUE)


# Create an empty list to store the resulting data frames
ts_list <- list()

# Create empty lists to store the filtered data frames
ts_list_trial_1 <- list()
ts_list_trial_2 <- list()

# Loop over the file names, read in each file, and store it in a data frame with the same name as the file
for (i in seq_along(csv_files)) {
  # Extract the file name without extension
  file_name <- gsub(".csv", "", basename(csv_files[i]))
  # Read in the CSV file
  data_frame <- read.delim(csv_files[i], header = TRUE, fill = TRUE, sep = ",", dec = ".")
  # Assign the data frame to an object with the same name as the file
  assign(file_name, data_frame)
  # Read in the CSV file and add the resulting data frame to the list with the same name as the file
  ts_list[[file_name]] <- read.delim(csv_files[i], header = TRUE, fill = TRUE, sep = ",", dec = ".")
}


# Loop over all the data frames in ts_list
for (i in seq_along(ts_list)) {
  # Extract the name of the data frame
  data_frame_name <- names(ts_list[i])
  # Check if the name ends with "trial1"
  if (grepl("trial1$", data_frame_name)) {
    # If it does, add the data frame to ts_list_trial_1
    ts_list_trial_1[[data_frame_name]] <- ts_list[[data_frame_name]]
  } else if (grepl("trial2$", data_frame_name)) {
    # If it ends with "trial2", add the data frame to ts_list_trial_2
    ts_list_trial_2[[data_frame_name]] <- ts_list[[data_frame_name]]
  }
}



```



RQA trial1
```{r}
RA_dyad1_trial1 <- crqa(ts1 = dyad01_p01_s01b_trial1$Region, ts2 = dyad01_p02_s01y_trial1$Region, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")



RA_dyad2_trial1 <- crqa(ts1 = dyad02_p03_s02b_trial1$Region, ts2 = dyad02_p04_s02y_trial1$Region, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")



RA_dyad3_trial1 <- crqa(ts1 = dyad03_p05_s03b_trial1$Region, ts2 = dyad03_p06_s03y_trial1$Region, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")



```



RQA trial2
```{r}
RA_dyad1_trial2 <- crqa(ts1 = dyad01_p01_s01b_trial2$Region, ts2 = dyad01_p02_s01y_trial2$Region, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")



RA_dyad2_trial2 <- crqa(ts1 = dyad02_p03_s02b_trial2$Region, ts2 = dyad02_p04_s02y_trial2$Region, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")



RA_dyad3_trial2 <- crqa(ts1 = dyad03_p05_s03b_trial2$Region, ts2 = dyad03_p06_s03y_trial2$Region, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")



```


Plotting Recurrence Plots
```{r}


```


PlottingDCRPs
```{r}
#### Trial 1


windowsize <- 150
sample_rate = 1/5
timecourse <- seq(-30,30, 1/5)
#timecourse = round( seq(-windowsize,windowsize,sample_rate)/sample_rate, digit = 1) #define x-axis of DCRP

DCRP_dyad1_trial1 <- drpfromts(ts1 = dyad01_p01_s01b_trial1$Region, ts2 = dyad01_p02_s01y_trial1$Region, windowsize = windowsize, datatype = "categorical", radius = 0.000001)

DCRP_dyad2_trial1 <- drpfromts(ts1 = dyad02_p03_s02b_trial1$Region, ts2 = dyad02_p04_s02y_trial1$Region, windowsize = windowsize, datatype = "categorical", radius = 0.000001)

DCRP_dyad3_trial1 <- drpfromts(ts1 = dyad03_p05_s03b_trial1$Region, ts2 = dyad03_p06_s03y_trial1$Region, windowsize = windowsize, datatype = "categorical", radius = 0.000001)




#### Trial 2




DCRP_dyad1_trial2 <- drpfromts(ts1 = dyad01_p01_s01b_trial2$Region, ts2 = dyad01_p02_s01y_trial2$Region, windowsize = windowsize, datatype = "categorical", radius = 0.000001)

DCRP_dyad2_trial2 <- drpfromts(ts1 = dyad02_p03_s02b_trial2$Region, ts2 = dyad02_p04_s02y_trial2$Region, windowsize = windowsize, datatype = "categorical", radius = 0.000001)

DCRP_dyad3_trial2 <- drpfromts(ts1 = dyad03_p05_s03b_trial2$Region, ts2 = dyad03_p06_s03y_trial2$Region, windowsize = windowsize, datatype = "categorical", radius = 0.000001)


```



Windowed Cross Recurrence Profile
```{r}
suppressWarnings(

winprofile_d1t1 <- wincrqa(ts1 = dyad01_p01_s01b_trial2$Region, ts2 = dyad01_p02_s01y_trial2$Region, windowstep = 5, windowsize = 50, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")
)

suppressWarnings(

winprofile_d2t1 <- wincrqa(ts1 = dyad02_p03_s02b_trial1$Region, ts2 = dyad02_p04_s02y_trial1$Region, windowstep = 5, windowsize = 50, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")
)
suppressWarnings(

winprofile_d3t1 <- wincrqa(ts1 = dyad03_p05_s03b_trial1$Region, ts2 = dyad03_p06_s03y_trial1$Region, windowstep = 5, windowsize = 50, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")
)
####

suppressWarnings(

winprofile_d1t2 <- wincrqa(ts1 = dyad01_p01_s01b_trial2$Region, ts2 = dyad01_p02_s01y_trial2$Region, windowstep = 5, windowsize = 50, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")
)
suppressWarnings(

winprofile_d2t2 <- wincrqa(ts1 = dyad02_p03_s02b_trial2$Region, ts2 = dyad02_p04_s02y_trial2$Region, windowstep = 5, windowsize = 50, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")
)
suppressWarnings(

winprofile_d3t2 <- wincrqa(ts1 = dyad03_p05_s03b_trial2$Region, ts2 = dyad03_p06_s03y_trial2$Region, windowstep = 5, windowsize = 50, delay = 1, embed = 1, rescale = 0, radius = 0.0001, normalize = 0, mindiagline = 2, minvertline = 2, tw = 0, whiteline = FALSE, recpt = FALSE, side = "both")

)



```




Plotting RPs, DCRPs and windowed recurrence plots
```{r}
#####   Recurrence Plots
#Trial1
image(RA_dyad1_trial1$RP[nrow(RA_dyad1_trial1$RP):1, ])
image(RA_dyad2_trial1$RP[nrow(RA_dyad2_trial1$RP):1, ])
image(RA_dyad3_trial1$RP[nrow(RA_dyad3_trial1$RP):1, ])

#Trial2
image(RA_dyad1_trial2$RP[nrow(RA_dyad1_trial2$RP):1, ])
image(RA_dyad2_trial2$RP[nrow(RA_dyad2_trial2$RP):1, ])
image(RA_dyad3_trial2$RP[nrow(RA_dyad3_trial2$RP):1, ])




#####   DCRPs
#Trial 1
plot(timecourse, DCRP_dyad1_trial1$profile, type = "l", lwd = 5, xlab = "Lag (seconds)", ylab = "RR", main = "Dyad1 - silence")
abline(v = timecourse[DCRP_dyad1_trial1$maxlag],
       lty = 2, col = "gray40", lwd = 3)
mtext(paste("Max Lag:", timecourse[DCRP_dyad1_trial1$maxlag], "sec."),
      at = timecourse[DCRP_dyad1_trial1$maxlag] + 1.2, side = 3, col = "red", line = -1.2,
      cex = .8)


plot(timecourse, DCRP_dyad2_trial1$profile, type = "l", lwd = 5, xlab = "Lag (seconds)", ylab = "RR", main = "Dyad2 - silence")
abline(v = timecourse[DCRP_dyad2_trial1$maxlag],
       lty = 2, col = "gray40", lwd = 3)
mtext(paste("Max Lag:", timecourse[DCRP_dyad2_trial1$maxlag], "sec."),
      at = timecourse[DCRP_dyad2_trial1$maxlag] + 1.2, side = 3, col = "red", line = -1.2,
      cex = .8)


plot(timecourse, DCRP_dyad3_trial1$profile, type = "l", lwd = 5, xlab = "Lag (seconds)", ylab = "RR", main = "Dyad3 - silence")
abline(v = timecourse[DCRP_dyad3_trial1$maxlag],
       lty = 2, col = "gray40", lwd = 3)
mtext(paste("Max Lag:", timecourse[DCRP_dyad3_trial1$maxlag], "sec."),
      at = timecourse[DCRP_dyad3_trial1$maxlag] + 1.2, side = 3, col = "red", line = -1.2,
      cex = .8)


#Trial 2
plot(timecourse, DCRP_dyad1_trial2$profile, type = "l", lwd = 5, xlab = "Lag (seconds)", ylab = "RR", main = "Dyad1 - conversation")
abline(v = timecourse[DCRP_dyad1_trial2$maxlag],
       lty = 2, col = "gray40", lwd = 3)
mtext(paste("Max Lag:", timecourse[DCRP_dyad1_trial2$maxlag], "sec."),
      at = timecourse[DCRP_dyad1_trial2$maxlag] + 1.2, side = 3, col = "red", line = -1.2,
      cex = .8)


plot(timecourse, DCRP_dyad2_trial2$profile, type = "l", lwd = 5, xlab = "Lag (seconds)", ylab = "RR", main = "Dyad2 - conversation")
abline(v = timecourse[DCRP_dyad2_trial2$maxlag],
       lty = 2, col = "gray40", lwd = 3)
mtext(paste("Max Lag:", timecourse[DCRP_dyad2_trial2$maxlag], "sec."),
      at = timecourse[DCRP_dyad2_trial2$maxlag] + 1.2, side = 3, col = "red", line = -1.2,
      cex = .8)


plot(timecourse, DCRP_dyad3_trial2$profile, type = "l", lwd = 5, xlab = "Lag (seconds)", ylab = "RR", main = "Dyad3 - conversation")
abline(v = timecourse[DCRP_dyad3_trial2$maxlag],
       lty = 2, col = "gray40", lwd = 3)
mtext(paste("Max Lag:", timecourse[DCRP_dyad3_trial2$maxlag], "sec."),
      at = timecourse[DCRP_dyad3_trial2$maxlag] + 1.2, side = 3, col = "red", line = -1.2,
      cex = .8)


####   Windowed Recurrence Plots
#Trial 1
plot(winprofile_d1t1$RR, type = "l", , xlab = "seconds", ylab = "RR", main = "Dyad1 - silence")
plot(winprofile_d2t1$RR, type = "l", , xlab = "seconds", ylab = "RR", main = "Dyad2 - silence")
plot(winprofile_d3t1$RR, type = "l", , xlab = "seconds", ylab = "RR", main = "Dyad3 - silence")

#Trial 2
plot(winprofile_d1t2$RR, type = "l", , xlab = "seconds", ylab = "RR", main = "Dyad1 - conversation")
plot(winprofile_d2t2$RR, type = "l", , xlab = "seconds", ylab = "RR", main = "Dyad2 - conversation")
plot(winprofile_d3t2$RR, type = "l", , xlab = "seconds", ylab = "RR", main = "Dyad3 - conversation")


```